version: "3"
services:
  application:
    image: ecommerce-app
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/ecommerce-app

  mysqldb:
    image: mysql:8.0.30
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce
    volumes:
      - /data/mysql
networks:
  springboot-db-net: